### ISSUE TITLE
"Illegal memory access was encountered" at material and light stage

### ISSUE THREAD

**Issue by dongchen-yang** [andyyankai/psdr-room#10]
Hi thanks for your great work! I was running fine_stage.py and after some iterations, I encountered this error message: `Critical Dr.Jit compiler failure: cuda_check(): API error 0700 (CUDA_ERROR_ILLEGAL_ADDRESS): "an illegal memory access was encountered" in C:\Users\86286\AppData\Local\Temp\pip-install-v6171yj4\psdr-jit_ee6bb5e417914fcd9416c08f23ce29aa\ext\drjit\ext\drjit-core\src\util.cpp:79. `  This error seems to occur every ~50 iterations but I can continue the script with the saved checkpoints so the preset optimization iterations (201 iterations) can be finished. 

I am wondering if you have this error and shall I worry about it?

**Comment by andyyankai** [comment]
I had the same issue, you can ignore this for now.
