### ISSUE TITLE
How to run object stage on custom data?

### ISSUE THREAD

**Issue by pcjccds** [andyyankai/psdr-room#11]
Hi @andyyankai , thanks for your exciting work. I'm wondering if we can test your work with a custom image. I don't find such description on how to do this, could you please give some help? 

Thanks!

**Comment by andyyankai** [comment]
"The example input data can be found here:
https://github.com/andyyankai/psdr-room/tree/main/object_stage/input/63
You will need to provide data in the style of this folder.
For example, to run your own scene using the folder named input/114514, execute the following command in the object_stage folder:
`python object_stage.py 114514`

**Comment by pcjccds** [comment]
@andyyankai Thanks for your quick reply. Yes, I can run the example, but how can I use my own data? I mean I suppose the input should only be an image? Or how should I generate data similar to the style of example 63? 

Besides, it seems that the model search is not included in the object stage code?

Thanks!

**Comment by pcjccds** [comment]
For example, I can see there is an `obj_init`, which should be something after model search / retrieve, but how can I get this init with a custom image? Could you proved that code?

**Comment by andyyankai** [comment]
Some part of the code especially for learning related are not public available from Adobe.
You can easily generate similar data by providing:
1. /input/63/depth: Depth map for the image
2. /input/63/mask: Segmentation from any state of art method
3. /input/63/obj_stage_init: Mesh predict for the scene and the mesh initial transform matrix in obj_stage_config.json
4. /input/63/camera.txt from https://github.com/jinlinyi/PerspectiveFields (camera fov, pitch and roll)
5. image_resize.png: input image

for model search, here is a encoder file for clip I use: 
https://github.com/andyyankai/psdr-room/blob/main/helper_scripts/utils/clip.py

**Comment by pcjccds** [comment]
Got it, thanks!
