### ISSUE TITLE
perspective camera with intrinsic matrix

### ISSUE THREAD

**Issue by ZheningHuang** [andyyankai/psdr-room#14]
Dear PSDR-room team,

Thank you for providing this amazing work.

I'm curious if you have the option to set the `psdr.PerspectiveCamera` with camera intrinsic parameters [fx, fy, c_x, c_y].

Upon reviewing [the source code of psdr-jit](https://github.com/andyyankai/psdr-jit/blob/0cf7a1d2ecfb7028ef422bb49b5eabf81378450b/include/psdr/sensor/perspective.h#L8), it appears that this is possible:

```cpp
SDR_CLASS_DECL_BEGIN(PerspectiveCamera, final, Sensor)
public:
    PerspectiveCamera(float fov_x, float near, float far) : m_fov_x(fov_x), m_near_clip(near), m_far_clip(far), m_use_intrinsic(false) {}
    PerspectiveCamera(float fx, float fy, float cx, float cy, float near, float far) 
        : m_fx(fx), m_fy(fy), m_cx(cx), m_cy(cy), m_near_clip(near), m_far_clip(far), m_use_intrinsic(true) {};
```

However, I am unsure if this functionality is usable in the Python API. I would appreciate your guidance on this matter.

Best
Zhening

**Comment by andyyankai** [comment]
Yes, there is also python binding to load camera intrinsic. You can check the psdr.cpp in psdr-jit for the python binding code. I can send an instruction later today(out for holiday)

**Comment by ZheningHuang** [comment]
This is great! thanks a lot! looking forward to it!

**Comment by andyyankai** [comment]
Something like this:
Let me know if this work.

```
psdr_sensor = psdr_jit.PerspectiveCamera(sensor['fx'], sensor['fy'], sensor['cx'], sensor['cy'], sensor['near'], sensor['far'])
psdr_sensor.to_world = Matrix4fD(sensor['to_world'].reshape(1, 4, 4))
psdr_scene.add_Sensor(psdr_sensor)
```
