### ISSUE TITLE
Question About Mask2former Model

### ISSUE THREAD

**Issue by s-takeru-endo** [andyyankai/psdr-room#16]
Dear PSDR-room team,

Thank you for sharing your work.

I have a question regarding the segmentation model. In your paper, you mentioned that you used **Mask2former**. Additionally, I checked the results for various images on the following site:
https://shuangz.com/projects/psdr-room-sa23/html/

However, in my own evaluations, I was unable to achieve accurate segmentation for each instance as shown on the site above.
For example, when segmenting a bed, the model separates the pillow and the bed frame into different segments.

Could you please let me know which specific Mask2former model you used? Also, if there are any techniques or considerations for achieving high quality segmentation, I would greatly appreciate your advice.

**Comment by andyyankai** [comment]
I simply use the default model for panoptic_seg and sem_seg.
