### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by qijiyaolinZGH** [andyyankai/psdr-room#2]
I hope you're well. 

I'm encountering a "Segmentation fault (core dumped)" error when I run "sc.configure()" in "obj_stage.py". From my research, it seems there might be a memory access issue with psdr_jit. Any guidance on resolving this would be appreciated.

I'm using an A40 GPU with driver version 535.129.03.

**Comment by andyyankai** [comment]
Are you able to run psdr-jit tutorial successfully?

**Comment by andyyankai** [comment]
Btw, I only test the code on windows, I haven’t check linux recently

**Comment by qijiyaolinZGH** [comment]
Running the psdr-jit tutorial has the same error. But I can run it on another 3080.The conda list of A40 is as follows:

`# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
blas                      1.0                    openblas  
brotli-python             1.0.9            py38h6a678d5_7  
ca-certificates           2023.08.22           h06a4308_0  
certifi                   2023.11.17       py38h06a4308_0  
cffi                      1.15.1           py38h74dc2b5_0  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
contourpy                 1.1.1                    pypi_0    pypi
cryptography              41.0.3           py38h130f0dd_0  
cudatoolkit               11.7.0              hd8887f6_10    nvidia
cycler                    0.12.1                   pypi_0    pypi
fonttools                 4.45.1                   pypi_0    pypi
idna                      3.4              py38h06a4308_0  
imageio                   2.33.0                   pypi_0    pypi
importlib-resources       6.1.1                    pypi_0    pypi
kiwisolver                1.4.5                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgfortran-ng            11.2.0               h00389a5_1  
libgfortran5              11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libopenblas               0.3.21               h043d6bf_0  
libstdcxx-ng              11.2.0               h1234567_1  
matplotlib                3.7.4                    pypi_0    pypi
ncurses                   6.4                  h6a678d5_0  
numpy                     1.24.4                   pypi_0    pypi
numpy-base                1.24.3           py38h1e6e340_0  
opencv-python             4.8.1.78                 pypi_0    pypi
openssl                   1.1.1w               h7f8727e_0  
packaging                 23.1             py38h06a4308_0  
pillow                    10.1.0                   pypi_0    pypi
pip                       23.3.1           py38h06a4308_0  
platformdirs              3.10.0           py38h06a4308_0  
pooch                     1.7.0            py38h06a4308_0  
psdr-jit                  0.1.5                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 23.2.0           py38h06a4308_0  
pyparsing                 3.1.1                    pypi_0    pypi
pysocks                   1.7.1            py38h06a4308_0  
python                    3.8.10               h12debd9_8  
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.2                  h5eee18b_0  
requests                  2.31.0           py38h06a4308_0  
scipy                     1.10.1                   pypi_0    pypi
setuptools                68.0.0           py38h06a4308_0  
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.2               h5eee18b_0  
tk                        8.6.12               h1ccaba5_0  
torch                     1.13.1+cu117             pypi_0    pypi
torchaudio                0.13.1+cu117             pypi_0    pypi
torchvision               0.14.1+cu117             pypi_0    pypi
typing-extensions         4.8.0                    pypi_0    pypi
urllib3                   1.26.18          py38h06a4308_0  
wheel                     0.41.2           py38h06a4308_0  
xz                        5.4.2                h5eee18b_0  
zipp                      3.17.0                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0  `

**Comment by qijiyaolinZGH** [comment]
psdr-jit tutorial is also not running successfully, same error is reported. But I was able to run it successfully on another 3090.

The conda list of A40 is as follows:

![Uploading Snipaste_2023-12-01_22-57-46.png…]()

**Comment by qijiyaolinZGH** [comment]
psdr-jit tutorial is also not running successfully, same error is reported. But I was able to run it successfully on another 3090.

The conda list of A40 is as follows:
<img width="370" alt="Snipaste_2023-12-01_22-57-46" src="https://github.com/andyyankai/psdr-room/assets/56566853/0f81b306-e30a-4786-919d-7276f0e619de">

**Comment by andyyankai** [comment]
Can you even run mitsuba3 or drjit (cuda version) on your A40 machine?

It is possible that optix cannot support on A40 or something. 

As far I know psdr-jit can run on most RTX machine but not sure for A40.

**Comment by qijiyaolinZGH** [comment]
Thanks!
