### ISSUE TITLE
How to structure data and format

### ISSUE THREAD

**Issue by Chunan-Yu** [andyyankai/psdr-room#5]
wonderful work. I ran into some trouble when running the material_light_stage project. I want to use my own data to run on your project, but I found that text_stage_config_auto.json cannot be constructed. Could you please share how to create the data?

**Comment by andyyankai** [comment]
You will need to generate your own. Take a look on what the file include. (there are some data are never been used like object categories) I will put a script and document on how to do that later.

**Comment by Chunan-Yu** [comment]
OK thank you, looking forward to your update.
