### ISSUE TITLE
Material stage for custom data

### ISSUE THREAD

**Issue by Pamogar** [andyyankai/psdr-room#7]
Hello, thank you for sharing this fantastic work.

I am currently working on automatic VR scenario generation, and I'm very interested in the material stage of this work for the walls, ceiling, and floor. Do you have any guidelines or recommendations for custom data formatting for this step?

Best regards.

Pau.

**Comment by andyyankai** [comment]
https://github.com/andyyankai/psdr-room/tree/main/material_light_stage/input/63/texture_stage_init

Take a look on the layout on these data, I will put more example and write a document for this later.. there is a json file to load all the mesh and texture/homogenous material, some value in the json is not needed and just for debug use(like category)

**Comment by pranavmalikk** [comment]
MatSynth was released recently which features 4,000 textures with licensing.  Since I wasn't able to find the substance materials/textures, maybe this could help with your documentation and others as well: https://huggingface.co/datasets/gvecchio/MatSynth
