### ISSUE TITLE
Code for Room Stage? 

### ISSUE THREAD

**Issue by nausithoe** [andyyankai/psdr-room#8]
Hi, I find your work very novel, code for object & material works great.

Do you plan on releasing the code for the room initialization & optimization?

Thanks!

**Comment by csyhping** [comment]
Same here. Will you release the complete code of all four stages, as mentioned in the paper? @andyyankai

**Comment by andyyankai** [comment]
I haven't planned to release the room stage for now. This can be quite trivial, achieved by simply optimizing the transformation matrix of a cube with the camera view from inside. You can use the depth with or without the wall segmentation as part of the loss function.
